name: container deployer action
description: a custom github action container deployer for dorapu
inputs:
  config-file:
    required: true
    description: >
      config file name to be looked up to. must be a TOML file.
      for example, "deploy.toml"
    default: deploy.toml
  dry-run:
    required: false
    description: >
      determine whether it is a dry run mode.
      helpful to build a CI to check if the docker build command will succeed
runs:
  using: docker
  image: Dockerfile
  env:
    CONFIG_FILE: ${{ inputs.config-file }}
    DRY_RUN: ${{ inputs.dry-run }}
