[package]
name = "container-deployer-action"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8"
base64 = "0.22"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12", features = ["blocking", "json"] }
