FROM docker.io/alpine:3.20

LABEL org.opencontainers.image.source=https://github.com/durapu/container-deployer-action
LABEL org.opencontainers.image.description="a simple example for the container deployer action"
LABEL org.opencontainers.image.licenses=MIT

ENTRYPOINT ["sh"]
