name: CD
run-name: trigger deployment process for ${{ github.sha }} by @${{ github.actor }}
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@v4
      - name: running deployment
        uses: ./
        with:
          config-file: deploy.toml
        env:
          GHCR_HOSTNAME: ${{ vars.GHCR_HOSTNAME }}
          GHCR_USERNAME: ${{ vars.GHCR_USERNAME }}
          GHCR_PASSWORD: ${{ secrets.GHCR_PASSWORD }}
